# Generated by Django 4.0.6 on 2022-07-25 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unsubscribeevent',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='unsubscribereason',
            options={'ordering': ['text']},
        ),
    ]
