# Generated by Django 4.0.6 on 2022-07-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_remove_lead_id_alter_lead_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email_mkt',
            field=models.BooleanField(default=True),
        ),
    ]
