# Generated by Django 4.0.6 on 2022-07-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_lead_email_mkt'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='subject',
            field=models.CharField(default='Teste', max_length=100),
            preserve_default=False,
        ),
    ]
