# Generated by Django 4.0.6 on 2022-07-22 16:48

from django.db import migrations, models
import django.db.models.deletion
import main.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='alt_a',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='alt_b',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='alt_c',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='alt_d',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer_alt',
            field=models.CharField(default='A', max_length=1, validators=[main.models.validate_alternative_answer]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='auxiliary_image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty_level',
            field=models.IntegerField(default=2, validators=[main.models.validate_difficulty_range]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='solution_image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='main.subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
