# Generated by Django 4.0.6 on 2022-07-23 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_exam_question_exam_year_question_exam_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='alt_a',
            new_name='alt_A',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='alt_b',
            new_name='alt_B',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='alt_c',
            new_name='alt_C',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='alt_d',
            new_name='alt_D',
        ),
    ]
