# Generated by Django 4.0.6 on 2022-07-23 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_alt_a_question_alt_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exam_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.exam'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.subject'),
        ),
    ]
